### PR TITLE
switching pattern library insert method to Javascript

### PR DESCRIPTION
**Pull request by brentonstrine**
#### Background Information
The previous Pattern Library used PHP includes, but Netlify does not support PHP. I am rewriting the "insert" script in Javascirpt. 

#### Impact
Removed the PHP and added the new file which is HTML with javascript. You can insert files using this code:

```
<script>insertHere("components/example.html");</script>
```

#### Issue
Solves: #93

### CODE REVIEW

**Comment by cocarson** [comment]
How does this approach effect search engine optimization? Can search engines read HTML that is added by JavaScript after the page has loaded?

**Comment by brentonstrine** [comment]
@cocarson I believe that at least Google crawls dynamically inserted text: https://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157

Open to doing this in other ways that are quick and simple if you have ideas.

**Comment by cocarson** [comment]
That's pretty cool! I didn't realize Google had that capability.

Do you think loading each of these modules separately is considered bad practice? I'm wondering how having many requests for the HTML pieces as opposed to a single request will effect site load performance and user experience.

**Comment by brentonstrine** [comment]
Definitely a bad practice but I'm trying not to dive too deep into a full-fledged MVC system here. 

To put it another way: using a chainsaw is definitely a more efficient way to chop down a tree than using an axe, and I'm using an axe here. But it's only one tree and we're many miles from the closest store that sells chain oil and gasoline. 

At the end of the day I expect less than 100 HTTP requests for this pattern library, which I think is totally reasonable.

**Comment by cocarson** [comment]
Ooooh is this only for the pattern library? I was under the impression student would be building out individual pages using this approach.

**Comment by brentonstrine** [comment]
@cocarson Yes, this is only for the pattern library, not the whole site. 

For the whole site, developers will come here and copy/paste the code to use since the site will be completely static.

**Pull request merged**
