### PR TITLE
Scrolling-banner-image

### PR DESCRIPTION
**Pull request by 24sint**
#### Background Information
#82  Create **scrolling-banner-image **
This is my first PR for the new refcode team website. I need someone to review my code.

#### Impact
It doesn't may have a visible impact right now, but it counts as the first draft to begin the project.

#### Issue
Solves: https://github.com/team-refcode/refcode.org/issues/82

### CODE REVIEW

**Comment by brentonstrine2** [comment]
I have a comment on how to make this work as a standalone component and work in the pattern library. 

First off, it's a component not a full HTML page, so the code should be an HTML fragment. So it doesn't need the `<!doctype>` or `<html>` or any of those tags. 

Secondly, if you use this template, then the `patternlibrary.html` page can automatically parse out the code in a neat way.

```
<div class="component" title="XXX" version="XXX">
  <includes>
  </includes>
  <style>
  </style>
  <markup>
  </markup>
</div>
```

So for this PR, it would look like this:

```

<div class="component" title="Scrolling Image Banner" version="1">
  <includes>
  </includes>
  <style>
  .image-banner1{
    background-image: url("http://placeimg.com/940/480/nature/sepia");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    background-attachment: fixed;
    height: 755px;
    margin-top: 230px;
  }
  .image-banner2{
    background-image: url("http://placeimg.com/940/480/nature");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    background-attachment: fixed;
    position: inherit;
    height: 755px;
    margin-top: 230px;
  }
  </style>

  <markup>
    <div class="image-banner1">
    </div>
    <div class="image-banner2">
    </div>
  </markup>
</div>
```

**Comment by brentonstrine** [comment]
Also, once you have the component formatted as above, you can copy the entire `<div>` directly into `patternlibrary.html` and it will look something like this:

image

**Comment by brentonstrine** [comment]
Great changes, @24sint !!! Get a review from one your your teammates and you should be good to go! One good way to get a review is to post a link to this PR so all they have to do is click the link! :D

**Comment by 24sint** [comment]
@MustafaAlsaeedi, thanks for reviewing my code. I understand the text holder is the heading of the section it will be given depending on our layout. But we can see when we meet together I can add it.

**Comment by MustafaAlsaeedi** [comment]
You can add text placeholder like `text` if you would like. I just don't see a place for it. @24sint

**Pull request merged**
