### PR TITLE
Created html5-boilerplate

### PR DESCRIPTION
**Pull request by MustafaAlsaeedi**
#### Background Information

To build html5-boilerplate as instructed in task #91.

#### Impact

Use the static html and css code.

#### Issue
Solves: Build project boilerplate #91

### CODE REVIEW

**Comment by 24sint** [comment]
Hi Mustafa, I like the HTML5 boilerplate template to use for any web project, but there are more new words in the code review which is not familiar with us.

**Comment by brentonstrine** [comment]
There is a lot in this boilerplate. You don't need it all. You will have to go through and pick just the items that you want. For example, it includes modernizr, which is a tool for detecting browser support of CSS. Also, it includes some favicon images, but they are not the refcode logo, they are a star. I left some Refcode icons in there for use.

**Comment by 24sint** [comment]
@brentonstrine, thank you that will be nice.

**Comment by MustafaAlsaeedi** [comment]
@brentonstrine I will reverse this request for now until I figure out what we exactly need to extract form this library and how to do it.

**Pull request merged**
