### PR TITLE
Added Mustafa's name to dev list

### PR DESCRIPTION
**Pull request by MustafaAlsaeedi**
I have added my name to the team's list upstream, I believe this is required for task #39.

### CODE REVIEW

**Comment by MustafaAlsaeedi** [comment]
There is a conflicting in teamcode.html. Also I do not see your changes online at: https://refcode.org/teamcode.html

**Comment by brentonstrine** [comment]
Hey Mustafa, you will have to manually resolve the merge conflict.

**Comment by MustafaAlsaeedi** [comment]
I feel like this could be a miss, hopefully, I am wrong.

**Comment by brentonstrine** [comment]
Also, you are correct, the changes going into matter will not automatically deploy. I turned that off. Now to deploy we will have to merge into the branch `prod` that I set up.

**Pull request merged**
