### PR TITLE
Fixed min-hight in the page layout

### PR DESCRIPTION
**Pull request by MustafaAlsaeedi**
#### Background Information

To fix an issue related to my previous task #86

#### Impact

hight: 100hv for the container layout used to cause rendering issues. I changed it to min-height. Also, I have a typo in the margin for the item aside: 25px instead of 5px.

#### Issue
Solves:  Task #86

### CODE REVIEW

**Comment by brentonstrine** [comment]
Don't forget to also update it in `patternlibrary.html`. Also, as this is an update to the component, you can increment the version number from `1.0` to `1.1`. 

The way you update versions is that for minor updates, you increment after the decimal, so that can go beyond `1.9` to `1.10`, `1.11`, ... `1.209` etc. But then when you make a major update (one that breaks backwards compatibility or that is a major rewrite) then you update the number before the decimal, e.g. `2.0`, `3.0` etc.

**Comment by MustafaAlsaeedi** [comment]
Thank you for the feedback @brentonstrine. Form what I understood, the same file that has been edited will be renamed (e.g. page_layout.html becomes page_layout_1.1.html).

**Comment by MustafaAlsaeedi** [comment]
Nvm @brentonstrine! You are most likely referring to the patternlibrary.html only.

**Comment by brentonstrine** [comment]
@mustafa exactly!

**Pull request merged**
