### PR TITLE
 volunteerOpportunity page text content is added

### PR DESCRIPTION
**Pull request by ayabaknu**

### CODE REVIEW

**Comment by brentonstrine** [comment]
I will look at this when I get a chance some time today.

**Comment by ayabaknu** [comment]
ok

**Review by brentonstrine — APPROVED** [review]

**Comment by brentonstrine** [comment]
Sorry it took me so long to get to this Tariku!

**Comment by ayabaknu** [comment]
no problem. what will be the next thing to do ?

**Pull request merged**
